care/urls.py
from django.contrib import admin
from django.urls import path, include
from . import  urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intensiv.urls')),
]

intensiv/urls.py
from django.urls import path, include
from .views import VitalSignsListView, VitalSignsCreateView, PatientListView, PatientDetailView
from .resources import PatientResource, VitalSignsResource
app_name = 'patients'
patient_resource = PatientResource()
vital_signs = VitalSignsResource()

urlpatterns = [
    path('', PatientListView.as_view(), name='patient_list'),
    path('vital/', VitalSignsListView.as_view(), name='vital_signs_list'),
    path('<int:pk>/', PatientDetailView.as_view(), name='patient_detail'),
    path('add/', VitalSignsCreateView.as_view(), name='vital_signs_create'),
    path('api/', include(patient_resource.urls)),
    path('api/', include(vital_signs.urls)),
]

intensiv/models.py
from django.db import models
from django.db.models import CharField
from django.utils import timezone
from django.urls import reverse


class Patient(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=3)
    address = models.CharField(max_length=255, default="")
    phone = models.PositiveIntegerField()
    date_in = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        """
        Здесь мы используем функцию reverse() для генерации URL для представления
        patient_detail, которое должно принимать параметр pk.
        """
        return reverse('patient_detail',  kwargs={'pk': self.pk})

    def __str__(self) -> CharField:
        return self.name


class VitalSigns(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    temperature = models.DecimalField(max_digits=4, decimal_places=2)
    heart_rate = models.PositiveIntegerField()
    respiratory_rate = models.PositiveIntegerField()
    blood_pressure_systolic = models.PositiveIntegerField()
    blood_pressure_diastolic = models.PositiveIntegerField()
    oxygen_saturation = models.PositiveIntegerField()
    measurement_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.patient.name

intensiv/forms.py
from django import forms
from .models import Patient


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('name', 'age', 'gender', 'address', 'phone', 'date_in')

intensiv/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from .models import VitalSigns, Patient
from django.views.generic import ListView
from .forms import PatientForm


class PatientListView(ListView):
    model = Patient
    template_name = 'patient_list.html'
    context_object_name = 'patient_list'


class VitalSignsListView(ListView):
    """
    VitalSignsListView - отображение списка всех записей о витальных функциях. 
    model указывает на модель, template_name определяет имя шаблона для отображения, 
    а context_object_name определяет имя переменной, которая будет передаваться в шаблон.
    """
    model = VitalSigns
    template_name = 'vital_signs_list.html'
    context_object_name = 'vital_signs'


class PatientDetailView(DetailView):
    """
    Отображение деталей записи о витальных функциях пациента.
    model, template_name и context_object_name определены так же, как и в VitalSignsListView.
    """
    model = Patient
    template_name = 'vital_signs_detail.html'
    context_object_name = 'patient_detail'


class VitalSignsCreateView(CreateView):
    """
    VitalSignsCreateView - форма для создания новой записи о витальных функциях. 
    model указывает на модель, template_name определяет имя шаблона для отображения формы, 
    а fields определяет поля модели, которые будут отображаться в форме.
    """
    model = VitalSigns
    template_name = 'vital_signs_form.html'
    fields = '__all__'


class VitalSignsUpdateView(UpdateView):
    """
    VitalSignsUpdateView - форма для обновления существующей записи о витальных функциях. 
    Параметры класса такие же, как в VitalSignsCreateView.
    """
    model = VitalSigns
    template_name = 'vital_signs_form.html'
    fields = '__all__'


class VitalSignsDeleteView(DeleteView):
    """
    VitalSignsDeleteView - форма для удаления записи о витальных функциях. model указывает на модель, 
    template_name определяет имя шаблона для отображения формы подтверждения удаления, 
    а success_url указывает URL-адрес, на который пользователь будет перенаправлен 
    после удаления записи.
    """
    model = VitalSigns
    template_name = 'vital_signs_confirm_delete.html'
    success_url = reverse_lazy('vital_signs_list')


class PatientListFormView(FormView):
    template_name = 'patient_list.html'
    form_class = PatientForm

    def form_valid(self, form):
        last_name = form.cleaned_data.get('last_name')
        first_name = form.cleaned_data.get('first_name')
        gender = form.cleaned_data.get('gender')
        patients = Patient.objects.filter(
            last_name__icontains=last_name,
            first_name__icontains=first_name,
            gender=gender,
        )
        context = {
            'form': form,
            'patients': patients,
        }
        return self.render_to_response(context)

intensiv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark navbar-light bg-dark">
        <a class="navbar-brand" href="#">Intensive Care Unit</a>
        <a class="navbar-brand" href="{% url 'patients:patient_list' %}">Patients   </a>
        <a class="navbar-brand" href="{% url 'patients:vital_signs_list' %}">Vital Signs</a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    
                </li>
            </ul>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    
</body>
</html>

intensiv/templates/patient_form.html
<!-- patient_list.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Patient List</title>
  </head>
  <body>
    <h1>Patient List</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Filter">
    </form>
    <table>
      <thead>
        <tr>
          <th>Last Name</th>
          <th>First Name</th>
          <th>Middle Name</th>
          <th>Gender</th>
          <th>Birth Date</th>
        </tr>
      </thead>
      <tbody>
        {% for patient in patients %}
          <tr>
            <td>{{ patient.last_name }}</td>
            <td>{{ patient.first_name }}</td>
            <td>{{ patient.middle_name }}</td>
            <td>{{ patient.get_gender_display }}</td>
            <td>{{ patient.birth_date }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5">No patients found.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

intensiv/templates/patient_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>List of Patients</h1>
  <table class="table mt-5 table-bordered table-striped table-hover">
      <thead class="table-dark">
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Name</th>
        <th>Age</th>
        <th>Gender</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patient_list %}
        <tr>
          <td>{{ patient.id }}</td>
          <td>{{ patient.date_in }}</td>
          <td> <a href="{% url 'patients:patient_detail' pk=patient.pk %}">{{patient.name}}</a></td>
          <td>{{ patient.age }}</td>
          <td>{{ patient.gender }}</td>
          <td>{{ patient.address }}</td>
          <td>{{ patient.phone}}</td>
          
        </tr>
      {% empty %}
        <tr>
          <td colspan="7">No patients found.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

intensiv/templates/vital_signs_detail.html
{% extends 'base.html' %}


{% block content %}
 
    <h1>{{ patient_detail }} Vital Signs</h1>
    <table class="table mt-5 table-bordered table-striped table-hover">
      <thead class=table-dark>
        <tr>
          <th>Measurement Time</th>
          <th>Temperature (C)</th>
          <th>Blood Pressure (mmHg)</th>
          <th>Heart Rate (bpm)</th>
          <th>Respiratory Rate (bpm)</th>
          <th>Oxygen Saturation (%)</th>
        </tr>
      </thead>
      <tbody>
          
      {% for vital_signs in patient_detail.vitalsigns_set.all %}
      <tr>
        <td>{{ vital_signs.measurement_date }}</td>
        <td>{{ vital_signs.temperature }}</td>
        <td>{{ vital_signs.blood_pressure_systolic}}/{{vital_signs.blood_pressure_diastolic }}</td>
        <td>{{ vital_signs.heart_rate }}</td>
        <td>{{ vital_signs.respiratory_rate }}</td>
        <td>{{ vital_signs.oxygen_saturation }}</td>

      </tr>
      {% empty %}
      <tr>
        <td colspan="6">No vital signs recorded.</td>
      </tr>


      {% endfor %}

      </tbody>
    </table>


{% endblock %}

intensiv/templates/vital_signs_list.html
{% extends 'base.html' %}
{% block content %}

  <h1>Vital Signs List</h1>
<table class="table mt-5 table-bordered table-striped table-hover">
      <thead class="table-dark">
      <tr>
        <th>Date</th>
        <th>Heart Rate</th>
        <th>Blood Press</th>
        <th>Resp Rate</th>
        <th>Satur</th>
        <th>Temp</th>
      </tr>
    </thead>
    <tbody>
                
        
      {% for vital_signs in vital_signs %}
        <tr>          
          <td>{{ vital_signs.measurement_date }}</td>
          <td>{{ vital_signs.heart_rate }}</td>
          <td>{{ vital_signs.blood_pressure_systolic}}/{{vital_signs.blood_pressure_diastolic }}</td>
          <td>{{ vital_signs.respiratory_rate }}</td>
          <td>{{ vital_signs.oxygen_saturation}}</td>
          <td>{{ vital_signs.temperature }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No vital signs recorded.</td>
        </tr>
      {% endfor %}
      </tbody>
  </table>
  <a href="{% url 'patients:vital_signs_create' %}">Add Vital Signs</a>
{% endblock %}